Greatly improved installation process :)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,86 +8,65 @@ CONFIGS=$(pwd)/files
 VIM_PATH=$CONFIGS/vim
 TERM_CONFIG_PATH=$CONFIGS/terminal/zshrc_config.sh
 
-
-check_success_message()
+# INSTALLATION FUNCTIONS 
+install_f_git()
 {
-    if [ "$1" -eq 0 ]; then
-        pass_message "$2" "succeeded $3"
+    # $1 = name
+    # $2 = path
+    # $3 = link
+    if [ -d $2 ]; then
+        pass_message "$1 already installed."
     else
-        fail_message "$2" "Failed $3"
-        STATUS=1
+        git clone $3 $2
+        check_success_message "$?" "installing $1"
     fi
 }
 
-install_brew()
+link_f_git()
 {
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    # $1 = name
+    # $2 = path
+    # $3 = link
+    if [ -L $1 ]; then
+        info_message "LINK" "Deleting old link to $1"
+        rm -i $1
+        if [ -e $1 ]; then
+            fail_message "FAIL" "failed deleting the link to $1"
+            return 1
+        fi
+    elif [ -e $1 ]; then
+        info_message "LINK" "File $1 already exists moving it to ~/.old_confs"
+        mkdir ~/.old_confs
+        mv $1 ~/.old_confs/
+        check_success_message "$?" "LINK" "Moving $1 to ~/.old_confs"
+    fi
+
+    info_message "LINK" "Linking terminal to $1"
+    ln -s $2 $1
+    check_success_message "$?" "linking $1"
 }
 
-install_git()
+# INSTALLATION OF MY SETUP :)
+termi()
 {
-    info_message "LINK" "Linking .gitconfig"
-    ln $CONFIGS/git/gitconfig ~/.gitconfig
-    check_success_message "$?" "LINK" "Linking gitconfig to ~/.gitconfig"
-
-    info_message "LINK" "Linking .gitignore"
-    ln $CONFIGS/git/gitignore ~/.gitignore
-    check_success_message "$?" "LINK" "Linking gitignore to ~/.gitignore"
-}
-
-install_vim()
-{
-    info_message "INST" "Installing Vim Config"
-    STATUS=0
-    info_message "LINK" "Linking .vim/ folder to ~/.vim"
-    ln -s $VIM_PATH/.vim   ~/.vim
-    check_success_message "$?" "LINK" "Linking vim/ folder to ~/.vim"
-
-    info_message "LINK" "Linking .vimrc to ~/.vimrc"
-    ln $VIM_PATH/.vimrc ~/.vimrc
-    check_success_message "$?" "LINK" "Linking .vimrc to ~/.vimrc"
-
-    # check if successfully linked
-    check_success_message "$STATUS" "INST" "installing vim config"
-}
-
-install_term()
-{
-    ln -s $CONFIGS/terminal ~/.term_confs
     info_message "INST" "Terminal Config"
-
-    ssh-add
-
-    if [ -d ~/.oh-my-zsh ]; then
-        pass_message "PASS" "oh-my-zsh already installed."
-    else
-        info_message "DWLD" "installing Oh-my-zsh"
-        git clone git@github.com:ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
-        check_success_message "$?" "installing oh-my-zsh"
-    fi
-
-    if [ -d ~/.oh-my-zsh/custom/plugins/zsh-z ]; then
-        pass_message "PASS" "zsh-z already installed."
-    else
-        info_message "DWLD" "installing zsh-z"
-        git clone git@github.com:agkozak/zsh-z.git ~/.oh-my-zsh/custom/plugins/zsh-z
-        check_success_message "$?" "installing zsh-z"
-    fi
-
-    if [ -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]; then
-        pass_message "PASS" "zsh-syntax-highlighting already installed."
-    else
-        info_message "DWLD" "installing zsh-syntax-highlighting"
-        git clone git@github.com:zsh-users/zsh-syntax-highlighting.git
-        mv zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins
-        check_success_message "$?" "installing zsh-syntax-highlighting"
-    fi
-
-
     STATUS=0
-    info_message "LINK" "Linking zshrc_config to ~/.zsrc"
-    ln $TERM_CONFIG_PATH ~/.zshrc
-    check_success_message "$?" "LINK" "Linking zshrc_config to ~/.zsrc"
+
+    # Install from remote
+    install_f_git "oh-my-zsh" ~/.oh-my-zsh "git@github.com:ohmyzsh/ohmyzsh.git"
+
+    install_f_git "zsh-z" \
+                  ~/.oh-my-zsh/custom/plugins/zsh-z \
+                  "git@github.com:agkozak/zsh-z.git"
+
+    install_f_git "zsh-syntax-highlighting" \
+                  ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting \
+                  "git@github.com:zsh-users/zsh-syntax-highlighting.git"
+
+
+    # link
+    link_f_git ~/.term_confs $CONFIGS/terminal
+    link_f_git ~/.zshrc $TERM_CONFIG_PATH
 
     info_message "SOUR" "Sourcing ~/.zshrc"
     source ~/.zshrc
@@ -95,14 +74,33 @@ install_term()
     end_message "term profile";
 }
 
-install_configs()
+vimi()
 {
-    install_vimrc
-    $RET=$?
-    if [[ $RET -eq 0 ]]; then
-        install_term
-        $RET=$?
-    fi
+    info_message "INST" "Installing Vim Config"
+    STATUS=0
 
-    end_message "vim and term profiles"
+    link_f_git ~/.vim .vim
+    link_f_git ~/.vimrc .vimrc
+
+    check_success_message "$STATUS" "installing vim config"
 }
+
+giti()
+{
+    link_f_git ~/.gitconfig $CONFIGS/git/gitconfig
+    link_f_git ~/.gitignore $CONFIG/git/gitignore
+
+    check_success_message "$STATUS" "installing git config"
+    info_message "Please replace your git name , mail and username"
+    echo "Using the following command:"
+    echo "git config --global user.name YOUR_NAME"
+    echo "git config --global user.email bla@bla.com"
+    echo "git config --global user.username YOUR_PSEUDO"
+}
+
+install_brew()
+{
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+}
+
+$1
